try:
    raise RuntimeError("發生錯誤")
except:
    print("錯誤發生")